### PR TITLE
Updated the Styling and Created a file structure.

### LINKED ISSUE #1: CSS style and file formating
Hello:)
I have noticed the file structure is not good. Also the styling can be better. I would like to work on that.

### PR DESCRIPTION
**Pull request by Bashamega**
close #1 
Hello:)
I have applied a cool design.

### CODE REVIEW

**Comment by BwnnyRxbbit** [comment]
OMG!! You are so talented! I love this!

**Comment by BwnnyRxbbit** [comment]
I have decided to delete the password thing as it is unnecessary.

**Comment by Bashamega** [comment]
> OMG!! You are so talented! I love this!

Your welcome. I am working on something for bark then I am going to start working on the timer

**Comment by Bashamega** [comment]
> I have decided to delete the password thing as it is unnecessary.

No problem, do you want help deleting it. It won't break the design

**Comment by Bashamega** [comment]
@BwnnyRxbbit Don't forget to delete the password thing that it inside the inner pages

**Comment by BwnnyRxbbit** [comment]
> @BwnnyRxbbit Don't forget to delete the password thing that it inside the inner pages

What is that? I'm still keeping a link to my insta though. It looks a bit funny now. Do you have any design ideas?

**Comment by BwnnyRxbbit** [comment]
Also would you be interested in adding a dark mode option to this?

**Comment by Bashamega** [comment]
> > @BwnnyRxbbit Don't forget to delete the password thing that it inside the inner pages
> 
> What is that? I'm still keeping a link to my insta though. It looks a bit funny now. Do you have any design ideas?

I mean the inner page has the input box.
image

**Comment by Bashamega** [comment]
> Also would you be interested in adding a dark mode option to this?

sure

**Comment by Bashamega** [comment]
For the design we can move your insta to the footer. which will give you more space for the content

**Comment by BwnnyRxbbit** [comment]
> For the design we can move your insta to the footer. which will give you more space for the content

That seems fine.

**Pull request merged**
