### PR TITLE
Dark Mode

### LINKED ISSUE #3: Dark Mode Theme
Just making an issue to help me remember that this repo needs a dark mode :)

### PR DESCRIPTION
**Pull request by Bashamega**
closes #3 
Hello:)
I have enabled dark mode for your website

### CODE REVIEW

**Comment by BwnnyRxbbit** [comment]
Would it be possible to make the toggle a button with a background?

**Comment by Bashamega** [comment]
> Would it be possible to make the toggle a button with a background?

Sure I am going to work on that

**Comment by BwnnyRxbbit** [comment]
> > Would it be possible to make the toggle a button with a background?
> 
> Sure I am going to work on that

And can you check disc?

**Comment by Bashamega** [comment]
> > > Would it be possible to make the toggle a button with a background?
> > 
> > 
> > Sure I am going to work on that
> 
> And can you check disc?

disc?

**Comment by BwnnyRxbbit** [comment]
> > > > Would it be possible to make the toggle a button with a background?
> > > 
> > > 
> > > Sure I am going to work on that
> > 
> > 
> > And can you check disc?
> 
> disc?

discord lol

**Comment by Bashamega** [comment]
> > > > > Would it be possible to make the toggle a button with a background?
> > > > 
> > > > 
> > > > Sure I am going to work on that
> > > 
> > > 
> > > And can you check disc?
> > 
> > 
> > disc?
> 
> discord lol

I replied

**Pull request merged**
